// Generates src/emoji-data.ts from @emoji-mart/data (a devDependency).
// Each entry is { c: native char, t: lowercase search terms (id + name + keywords) }.
// Run with: node scripts/gen-emoji.mjs
import { createRequire } from "module";
import fs from "fs";

const require = createRequire(import.meta.url);
const data = require("@emoji-mart/data");

const out = [];
for (const id of Object.keys(data.emojis)) {
  const e = data.emojis[id];
  const native = e.skins && e.skins[0] && e.skins[0].native;
  if (!native) continue;
  // Dedupe tokens (name + keywords; the id duplicates the name) to keep the
  // bundle lean while preserving keyword search.
  const tokens = new Set();
  for (const w of [e.name, ...(e.keywords || [])]
    .join(" ")
    .toLowerCase()
    .replace(/_/g, " ")
    .split(/\s+/)) {
    if (w) tokens.add(w);
  }
  out.push({ c: native, t: [...tokens].join(" ") });
}

const body =
  "// Generated by scripts/gen-emoji.mjs from @emoji-mart/data — do not edit.\n" +
  "export interface EmojiEntry {\n  /** native emoji character */\n  c: string;\n  /** lowercase search terms (id + name + keywords) */\n  t: string;\n}\n\n" +
  "export const EMOJI: EmojiEntry[] = " +
  JSON.stringify(out) +
  ";\n";

fs.writeFileSync("src/emoji-data.ts", body);
console.log("wrote", out.length, "emojis to src/emoji-data.ts");
